modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "croaklib"
version = "${version}"
displayName = "CroakLib"
authors = "CroakAndRoll"
description = '''
Library mod for my common code.
'''
logoFile = "icon.png"

[[dependencies.croaklib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.croaklib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.croaklib]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
